// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFG1r3Ob0HsGy0XxuAow50OmRqX6Cv244',
    appId: '1:777216415910:web:043e413290614e3abffc67',
    messagingSenderId: '777216415910',
    projectId: 'ecommerce-app-b0035',
    authDomain: 'ecommerce-app-b0035.firebaseapp.com',
    storageBucket: 'ecommerce-app-b0035.appspot.com',
    measurementId: 'G-NHXGFL79KR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpA53VuuM6_a2dpDBvpEAFqX-sfjxVyfg',
    appId: '1:777216415910:android:9e5884f39df753a2bffc67',
    messagingSenderId: '777216415910',
    projectId: 'ecommerce-app-b0035',
    storageBucket: 'ecommerce-app-b0035.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPRFa9eOqyCYx7sJX0KpwH33hfrd2ekno',
    appId: '1:777216415910:ios:0547ce149a5ee76abffc67',
    messagingSenderId: '777216415910',
    projectId: 'ecommerce-app-b0035',
    storageBucket: 'ecommerce-app-b0035.appspot.com',
    iosClientId: '777216415910-pclcldki2iviqv1h2sofjifmqfi6fqan.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
